# Generated by Django 4.2.13 on 2026-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, unique=True)),
                ('permissions', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('producer_operator', 'Producer Manager'), ('producer_onboarding', 'Producer Onboarding'), ('producer_support', 'Producer Support')], default='operator', max_length=30),
        ),
    ]
