# Generated by Django 4.2.13 on 2026-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rolepermission_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.TextField(blank=True, help_text='Product description and goals used by AI to evaluate operator calls')),
                ('prompt_survey', models.TextField(blank=True, help_text='Custom instructions for evaluating survey/casdev quality (leave blank for default)')),
                ('prompt_explanation', models.TextField(blank=True, help_text='Custom instructions for evaluating product explanation quality (leave blank for default)')),
                ('prompt_overall', models.TextField(blank=True, help_text='Custom instructions for evaluating overall call quality (leave blank for default)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRM Settings',
            },
        ),
    ]
