# Generated by Django 4.2.13 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_evaluation_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('producer_operator', 'Producer Manager'), ('producer_onboarding', 'Producer Onboarding'), ('producer_support', 'Producer Support')], db_index=True, default='operator', max_length=30),
        ),
    ]
