# Generated by Django 4.2.13 on 2026-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='title',
            field=models.CharField(default='Generating report…', max_length=250),
        ),
    ]
