# Generated by Django 4.2.13 on 2026-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_aireport_error_message_aireport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='report_type',
            field=models.CharField(choices=[('partners', 'Partners'), ('producers', 'Producers')], db_index=True, default='partners', max_length=20),
        ),
    ]
