# Generated by Django 4.2.13 on 2026-04-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_brandsituationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Identifier from JOB_REGISTRY', max_length=64)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('startup', 'Startup'), ('manual', 'Manual')], default='schedule', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(blank=True, help_text='Short result message', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_id', '-started_at'], name='reports_aij_job_id_4fb6ff_idx')],
            },
        ),
    ]
