# Generated by Django 4.2.13 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_aijobrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='brandsituationreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='producerupdatereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
    ]
