# Generated by Django 4.2.13 on 2026-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='callback_later',
            field=models.BooleanField(default=False, help_text='Need to call back later'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_missed_call',
            field=models.BooleanField(default=False, help_text='Operator did not reach the partner'),
        ),
    ]
