# Generated by Django 4.2.13 on 2026-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_add_missed_call_callback_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/transcripts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='transcription_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='', max_length=20),
        ),
    ]
