# Generated by Django 4.2.13 on 2026-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_transcript_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='summary_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='', max_length=20),
        ),
    ]
