# Generated by Django 4.2.13 on 2026-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_add_summary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='callback_later',
            field=models.BooleanField(db_index=True, default=False, help_text='Need to call back later'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_missed_call',
            field=models.BooleanField(db_index=True, default=False, help_text='Operator did not reach the partner'),
        ),
    ]
