# Generated by Django 4.2.13 on 2026-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_callback_later_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='call_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='diarized_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_explanation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_explanation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_overall',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_overall_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_survey',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_survey_comment',
            field=models.TextField(blank=True),
        ),
    ]
