# Generated by Django 4.2.13 on 2026-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_add_diarization_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quality_feedback',
            field=models.TextField(blank=True),
        ),
    ]
