# Generated by Django 4.2.13 on 2026-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_add_quality_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quality_explanation_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_overall_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='quality_survey_detail',
            field=models.TextField(blank=True),
        ),
    ]
