# Generated by Django 4.2.13 on 2026-04-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0008_add_detailed_quality_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calls_analyzed', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], default='generating', max_length=12)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-period_start'],
                'unique_together': {('operator', 'feedback_type', 'period_start')},
            },
        ),
    ]
