# Generated by Django 4.2.13 on 2026-04-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_add_errors_and_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='summary_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='summary_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='summary_retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='transcription_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='transcription_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='transcription_retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorfeedback',
            name='generation_retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatorfeedback',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorfeedback',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
