# Generated by Django 4.2.13 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_summary_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='summary_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transcription_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorfeedback',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='generating', max_length=12),
        ),
    ]
