# Generated by Django 4.2.13 on 2026-04-23 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0013_callinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(db_index=True)),
                ('date_to', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_insights', models.PositiveIntegerField(default=0)),
                ('unique_partners', models.PositiveIntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, help_text='Executive summary in English')),
                ('clusters_json', models.JSONField(blank=True, default=dict)),
                ('rendered_markdown', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='callinsight',
            new_name='contacts_ca_partner_a34170_idx',
            old_name='contacts_ca_partner_0f90_idx',
        ),
        migrations.RenameIndex(
            model_name='callinsight',
            new_name='contacts_ca_status_f28880_idx',
            old_name='contacts_ca_status_8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='callinsight',
            new_name='contacts_ca_telegra_e7ffea_idx',
            old_name='contacts_ca_telegra_3c1d_idx',
        ),
        migrations.AddField(
            model_name='insightaggregate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_aggregates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='insightaggregate',
            index=models.Index(fields=['-created_at'], name='contacts_in_created_26382f_idx'),
        ),
        migrations.AddIndex(
            model_name='insightaggregate',
            index=models.Index(fields=['date_from', 'date_to'], name='contacts_in_date_fr_0d5a36_idx'),
        ),
        migrations.AddIndex(
            model_name='insightaggregate',
            index=models.Index(fields=['status', '-last_attempt_at'], name='contacts_in_status_93ef53_idx'),
        ),
    ]
