# Generated by Django 4.2.13 on 2026-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_insightaggregate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightaggregate',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual ad-hoc report'), ('rolling_30d', 'Rolling 30 days'), ('rolling_60d', 'Rolling 60 days'), ('rolling_180d', 'Rolling 180 days'), ('rolling_all', 'All time')], db_index=True, default='manual', max_length=20),
        ),
    ]
