# Generated by Django 4.2.13 on 2026-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='stage',
            field=models.CharField(choices=[('agreed', 'Договорились'), ('signed', 'Подписали'), ('products_received', 'Список товаров'), ('ready_to_sell', 'Готовы продавать'), ('in_store', 'В магазине'), ('support_new', 'New Request'), ('support_wip', 'In Progress'), ('support_waiting', 'Awaiting Client'), ('support_review', 'Review'), ('support_done', 'Completed')], db_index=True, default='agreed', max_length=30),
        ),
    ]
