# Generated by Django 4.2.13 on 2026-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_alter_producer_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('demo_done', 'Demo Done'), ('agreement_sent', 'Agreement Sent'), ('docs_signed', 'Docs Signed'), ('integration', 'Integration'), ('live', 'Live'), ('agreed', 'Agreed'), ('signed', 'Signed'), ('products_received', 'Products Received'), ('ready_to_sell', 'Ready to Sell'), ('in_store', 'In Store')], db_index=True, default='new_lead', max_length=30),
        ),
    ]
