# Generated by Django 4.2.13 on 2026-04-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_alter_producer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='certifications',
            field=models.TextField(blank=True, help_text='Comma-separated: GMP, ISO, FSSAI, etc.'),
        ),
        migrations.AddField(
            model_name='producer',
            name='communication_status',
            field=models.TextField(blank=True, help_text='Comma-separated communication status tags'),
        ),
        migrations.AddField(
            model_name='producer',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Key contacts, emails, phones'),
        ),
        migrations.AddField(
            model_name='producer',
            name='control_date',
            field=models.DateField(blank=True, db_index=True, help_text='Next follow-up date', null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='cooperation_potential',
            field=models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak'), ('no_response', 'No Response Yet')], default='medium', max_length=15),
        ),
        migrations.AddField(
            model_name='producer',
            name='next_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producer',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='producer',
            name='product_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of SKUs / catalog size', null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='product_type',
            field=models.CharField(blank=True, help_text='Type / category of products', max_length=255),
        ),
    ]
