# Generated by Django 4.2.13 on 2026-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_add_pharma_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='last_contact',
            field=models.DateField(blank=True, db_index=True, help_text='Date of last contact', null=True),
        ),
    ]
