# Generated by Django 4.2.13 on 2026-04-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0006_producer_last_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='planned_connection_date',
            field=models.DateField(blank=True, help_text='Planned onboarding / connection date', null=True),
        ),
    ]
