# Generated by Django 4.2.13 on 2026-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0008_abandoned_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='stage',
            field=models.CharField(choices=[('interest', 'Interest'), ('in_communication', 'In Communication'), ('negotiation', 'Подписываем контракт'), ('contract_signed', 'Contract Signed'), ('on_platform', 'On the Platform'), ('stopped', 'Stopped'), ('agreed', 'Agreed'), ('signed', 'Signed'), ('products_received', 'Products Received'), ('ready_to_sell', 'Ready to Sell'), ('in_store', 'In Store')], db_index=True, default='interest', max_length=30),
        ),
    ]
