# Generated by Django 4.2.13 on 2026-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0009_alter_producer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='asana_task_gid',
            field=models.CharField(blank=True, db_index=True, help_text='Asana task gid — used for syncing comments back from Asana', max_length=64),
        ),
        migrations.AddField(
            model_name='producercomment',
            name='asana_story_id',
            field=models.CharField(blank=True, db_index=True, help_text='Asana story gid — set when comment was imported from Asana', max_length=64),
        ),
    ]
