# Generated by Django 4.2.13 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0011_alter_producer_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='cooperation_potential',
            field=models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak'), ('no_response', 'No Response Yet')], db_index=True, default='medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='producertask',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='producertask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10),
        ),
    ]
