# Generated by Django 4.2.13 on 2026-04-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producers', '0013_alter_producer_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateTimeField(db_index=True)),
                ('period_to', models.DateTimeField(db_index=True)),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled (Fri 16:00 IST)'), ('manual', 'Manual refresh')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_new_producers', models.PositiveIntegerField(default=0)),
                ('total_changed_producers', models.PositiveIntegerField(default=0)),
                ('total_comments_considered', models.PositiveIntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, help_text='Executive summary in English.')),
                ('new_producers_json', models.JSONField(blank=True, default=list, help_text='Array of new-producer cards.')),
                ('changes_json', models.JSONField(blank=True, default=list, help_text='Array of significant change cards (LLM-filtered).')),
                ('rendered_markdown', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_weekly_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_to', '-created_at'],
                'indexes': [models.Index(fields=['-period_to'], name='producers_p_period__2950e6_idx'), models.Index(fields=['status', '-last_attempt_at'], name='producers_p_status_807242_idx')],
            },
        ),
    ]
