# Generated by Django 4.2.13 on 2026-04-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('user_id', models.CharField(blank=True, help_text='ID from the platform', max_length=100)),
                ('type', models.CharField(choices=[('partner', 'Partner'), ('medic', 'Medic')], default='partner', max_length=20)),
                ('category', models.CharField(choices=[('doctor', 'Doctor'), ('fitness_trainer', 'Fitness Trainer'), ('blogger', 'Blogger'), ('other', 'Other')], default='other', max_length=30)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('new', 'New'), ('trained', 'Trained'), ('set_created', 'Medical Set Created'), ('has_sale', 'Has Sale')], default='new', max_length=20)),
                ('medical_sets_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('paid_orders_count', models.PositiveIntegerField(default=0)),
                ('paid_orders_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unpaid_orders_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referrals_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
