# Generated by Django 4.2.13 on 2026-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='control_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_support', 'На сопровождении'), ('closed', 'Закрыто')], default='new', max_length=20),
        ),
    ]
