# Generated by Django 4.2.13 on 2026-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_control_date_partner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_support', 'In Support'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
