# Generated by Django 4.2.13 on 2026-04-14 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='control_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
