# Generated by Django 4.2.13 on 2026-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('trained', 'Trained'), ('set_created', 'Medical Set Created'), ('has_sale', 'Has Sale'), ('no_answer', 'No Answer'), ('declined', 'Declined'), ('no_sales', 'No Sales')], default='new', max_length=20),
        ),
    ]
