# Generated by Django 4.2.13 on 2026-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_add_no_answer_declined_no_sales_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('trained', 'Trained'), ('set_created', 'Medical Set Created'), ('has_sale', 'Has Sale'), ('no_answer', 'Dead (No Answer)'), ('declined', 'Dead (Declined)'), ('no_sales', 'Dead (No Sales)')], default='new', max_length=20),
        ),
    ]
