# Generated by Django 4.2.13 on 2026-04-15 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_add_stage_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='control_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='partner',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('trained', 'Trained'), ('set_created', 'Medical Set Created'), ('has_sale', 'Has Sale'), ('no_answer', 'Dead (No Answer)'), ('declined', 'Dead (Declined)'), ('no_sales', 'Dead (No Sales)')], db_index=True, default='new', max_length=20),
        ),
    ]
