# Generated by Django 4.2.13 on 2026-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_partner_control_date_alter_partner_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='whatsapp_added',
            field=models.BooleanField(db_index=True, default=False, help_text='Partner has been added to our WhatsApp channel'),
        ),
    ]
