# Generated by Django 4.2.13 on 2026-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_rename_trained_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('fitness_trainer', 'Fitness Trainer'), ('blogger', 'Blogger'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_support', 'In Support'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('partner', 'Partner'), ('medic', 'Medic')], db_index=True, default='partner', max_length=20),
        ),
    ]
